import os
import sys

env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR'];
LIB_DIR=os.environ['LIB_DIR'];

env['LIBS'] = ['assets', 'jerryscript'] + env['LIBS']

env.Program(os.path.join(BIN_DIR, 'runScript'), ["run_js.c", 'tk_jerryscript.c'])
env.Library(os.path.join(LIB_DIR, 'awtk-jerryscript'), ['tk_jerryscript.c'])





