import os
import sys

env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR'];

print(env['LIBPATH'])

env['LIBS'] = ['resource', 'jerry-ext', 'jerry-core', 'jerry-port-default'] + env['LIBS']
env.Program(os.path.join(BIN_DIR, 'runScript'), ["run_js.c", 'tk_jerryscript.c', 'jerryscript_helper.c'])




