import os
import sys

env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR'];

env['LIBS'] = ['assets', 'jerryscript'] + env['LIBS']
env.Program(os.path.join(BIN_DIR, 'runScript'), ["run_js.c", 'tk_jerryscript.c'])




