import os
import sys

env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR'];
LIB_DIR=os.environ['LIB_DIR'];

env.Library(os.path.join(LIB_DIR, 'awtk-jerryscript'), ['c/utils.c','c/tk_jerryscript.c'])
env.Program(os.path.join(BIN_DIR, 'awtkRun'), ['c/main.c', 'assets.c'])





